### ISSUE TITLE
calculations on front end (browser)

### ISSUE THREAD

**Issue by ragnika** [BluuArc/project-sparkle#1]
Not an issue. just a suggestion.

I haven't ran the code on the front end, but it does look to be possible to run it on the client's browser as opposed to run the code server side.
then have the server just supply the summary of the datamine or singular unit data on demand.

I'll do a test run when i get back from work.

**Comment by BluuArc** [comment]
Just did a quick test via the Chrome Web Debugger Console. 

It is possible to run the calculations on the client's browser, but I noticed that the page I was on was unresponsive during the calculations. 

Because of this, I plan to keep the calculations mostly server-side (wouldn't want users to think the program froze, crashed, or something like that). I may implement an option to run the calculations on the client's browser in the future, though.

**Comment by ragnika** [comment]
yeah, i was afraid it might take a bit too much resources.

fair enough then

**Comment by BluuArc** [comment]
The current version is now a full browser based spark simulator. I was able to figure out how to run the calculations on the client side using web workers.
